#!/usr/bin/env bash
set -euo pipefail

############################
# Usage
############################
usage() {
    cat <<EOF
Usage: $0 [options]

Options:
  -m <models>       Model(s) to train, comma-separated
                    (default: wayformer, scenetokens, causal_scenetokens, safe_scenetokens, scenetransformer, autobot, mtr)
  -d <devices>      Devices (e.g. 0 or 0,1)
                    (default: 0)
  -b <benchmark>    Benchmark to evaluate on (one of "causal_agents", "ego_safeshift_causal", "environments")
                    (default: "causal_agents")
  -g <gen_model>    Model used to generate the selection strategy files
                    (e.g. scenetokens, wayformer, safe_scenetokens)
                    Ignored for -t random (uses "no_model" folder automatically)
                    (default: "scenetokens")
  -s <strategies>   Strategy/strategies, comma-separated
                    (default depends on -t: token→all token strategies, kmeans→all kmeans strategies,
                     random→random_drop, dentp→den_tp)
                    Custom strategies must be valid for the selected type.
  -p <percentages>  Percentage(s), comma-separated
                    (default: 0.45, 0.55, 0.65, 0.75, 0.85, 0.95)
  -t <type>         Type of sample selection strategy (one of "token", "kmeans", "random", "dentp")
                    (default: "token")
  -n                Dry run (print commands, do not execute)
  -h                Show this help message

Path resolution:
  Files are loaded from: ./meta/selection_strategies/<benchmark>/<gen_model>/<type>/
  For random strategies the model folder is always "no_model".

Examples:
  # Run with all defaults
  $0

  # Token strategies for scenetokens model on causal_agents benchmark
  $0 -b causal_agents -g scenetokens -t token -m scenetokens

  # KMeans strategies generated by wayformer
  $0 -b causal_agents -g wayformer -t kmeans -m wayformer

  # Random baseline (no gen_model needed)
  $0 -b causal_agents -t random -m wayformer

  # Multiple models and devices
  $0 -m wayformer,scenetransformer -d 0,1

  # Custom strategies
  $0 -s token_random_drop,gumbel_token_hamming_drop

  # Custom percentages
  $0 -p 0.5,0.7,0.9

  # Dry run to preview commands
  $0 -b causal_agents -g scenetokens -t token -m scenetokens -n
EOF
    exit 1
}

############################
# Defaults
############################
DEFAULT_MODELS=(
    wayformer
    scenetokens
    causal_scenetokens
    safe_scenetokens
    scenetransformer
    autobot
    mtr
)
DEFAULT_DEVICES="0"
DEFAULT_BENCHMARK="causal_agents"
DEFAULT_GEN_MODEL="scenetokens"
DEFAULT_SAMPLE_SELECTION_TYPE="token"
KMEANS_STRATEGIES=(
    kmeans_random_drop
    simple_kmeans_cosine_drop
    gumbel_kmeans_cosine_drop
    vocab_cluster_hamming_drop
    vocab_cluster_jaccard_drop
)
RANDOM_STRATEGIES=(
    random_drop
)
TOKEN_STRATEGIES=(
    token_random_drop
    simple_token_jaccard_drop
    simple_token_hamming_drop
    gumbel_token_jaccard_drop
    gumbel_token_hamming_drop
    vocab_token_hamming_drop
    vocab_token_jaccard_drop
)
DEN_TP_STRATEGY=(
    den_tp
)
DEFAULT_PERCENTAGES=(0.45 0.55 0.65 0.75 0.85 0.95)
dry_run=false

############################
# Parse arguments
############################
models=()
devices="$DEFAULT_DEVICES"
benchmark="$DEFAULT_BENCHMARK"
gen_model="$DEFAULT_GEN_MODEL"
strategies=()
percentages=()
selection_type="$DEFAULT_SAMPLE_SELECTION_TYPE"

while getopts ":m:d:b:g:s:p:t:nh" opt; do
    case $opt in
        m) IFS=',' read -ra models <<< "$OPTARG" ;;
        d) devices="$OPTARG" ;;
        b) benchmark="$OPTARG" ;;
        g) gen_model="$OPTARG" ;;
        s) IFS=',' read -ra strategies <<< "$OPTARG" ;;
        p) IFS=',' read -ra percentages <<< "$OPTARG" ;;
        t) selection_type="$OPTARG" ;;
        n) dry_run=true ;;
        h) usage ;;
        \?) echo "Invalid option: -$OPTARG" >&2; usage ;;
        :) echo "Option -$OPTARG requires an argument." >&2; usage ;;
    esac
done

############################
# Validate benchmark
############################
valid_benchmarks=(causal_agents ego_safeshift_causal environments)
if ! printf '%s\n' "${valid_benchmarks[@]}" | grep -qx "$benchmark"; then
    echo "Error: benchmark '$benchmark' is not valid. Valid benchmarks: ${valid_benchmarks[*]}" >&2
    exit 1
fi

############################
# Apply defaults if empty
############################
[[ ${#models[@]} -eq 0 ]] && models=("${DEFAULT_MODELS[@]}")
[[ ${#percentages[@]} -eq 0 ]] && percentages=("${DEFAULT_PERCENTAGES[@]}")

if [[ "$selection_type" == "token" ]]; then
    valid_strategies=("${TOKEN_STRATEGIES[@]}")
elif [[ "$selection_type" == "kmeans" ]]; then
    valid_strategies=("${KMEANS_STRATEGIES[@]}")
elif [[ "$selection_type" == "random" ]]; then
    valid_strategies=("${RANDOM_STRATEGIES[@]}")
elif [[ "$selection_type" == "dentp" ]]; then
    valid_strategies=("${DEN_TP_STRATEGY[@]}")
else
    echo "Error: selection_type must be one of 'token', 'kmeans', 'random', 'dentp', got '$selection_type'" >&2
    exit 1
fi

if [[ ${#strategies[@]} -eq 0 ]]; then
    strategies=("${valid_strategies[@]}")
else
    for s in "${strategies[@]}"; do
        if ! printf '%s\n' "${valid_strategies[@]}" | grep -qx "$s"; then
            echo "Error: strategy '$s' is not valid for type '$selection_type'. Valid strategies: ${valid_strategies[*]}" >&2
            exit 1
        fi
    done
fi

############################
# Resolve selection path
############################
if [[ "$selection_type" == "random" ]]; then
    model_folder="no_model"
else
    model_folder="$gen_model"
fi
selection_path="./meta/selection_strategies/${benchmark}/${model_folder}/${selection_type}"

############################
# Run experiments
############################
for model in "${models[@]}"; do
    for strategy in "${strategies[@]}"; do
        for pct in "${percentages[@]}"; do
            sweep_type="_${strategy}_${pct}_${selection_type}"

            cmd=(
                uv run -m scenetokens.train
                model="$model"
                trainer.devices="[$devices]"
                paths="$benchmark"
                sample_selection_strategy="$strategy"
                sample_selection_path="$selection_path"
                percentage="$pct"
                sweep_type="$sweep_type"
            )

            echo "--------------------------------------------------"
            echo "Model:          $model"
            echo "Devices:        $devices"
            echo "Benchmark:      $benchmark"
            echo "Gen model:      $model_folder"
            echo "Strategy:       $strategy"
            echo "Percentage:     $pct"
            echo "Selection path: $selection_path"
            echo

            if $dry_run; then
                echo "[DRY RUN] ${cmd[*]}"
            else
                "${cmd[@]}"
            fi
        done
    done
done
